title: Shamsul Arefin # your name (or website title) here
logo: "/images/my_cropped_image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a final Year Masters Student at the University of Regina
  <br><br>
  I like to learn new things, solve problems. I have over 3 years of experience in working with Mobile Application development, Django Rest Framework, Django CMS
  frameworks. During my tenure I also gained client communication, project management skills.
  You can find some of my projects in my portfolio page. I can be reached via my email : arefin.4414@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/shamsul-arefin/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
